version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network
    env_file:
      - frontend/.env

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app_network
    env_file:
      - backend/.env

networks:
  app_network:
